synthetic-package: false
arb-dir: lib/l10n
template-arb-file: app_en.arb
preferred-supported-locales: en
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.json