name: dr_ai
description: "Dr.AI是一個AI驅動的智能醫生應用程式，整合了語音識別、文字轉語音和AI聊天功能，用於健康諮詢和醫療記錄管理。"
repository: https://github.com/old-cookie/dr_ai
issue_tracker: https://github.com/old-cookie/dr_ai/issues
publish_to: 'none'
version: 5.9.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_text_kit: ^4.2.2
  bitsdojo_window: ^0.1.6
  bmi_calculator: ^1.0.0
  crop_your_image: ^2.0.0
  cunning_document_scanner: ^1.2.3
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  datetime_loop: ^1.2.0
  dropdown_search: ^6.0.2
  duration_picker: ^1.2.0
  dynamic_color: ^1.7.0
  encrypt_shared_preferences: ^0.9.8
  file_picker: ^9.0.1
  file_selector: ^1.0.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.13
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^18.0.1
  flutter_markdown: ^0.7.1
  flutter_tesseract_ocr: ^0.4.28
  flutter_timezone: ^4.1.0
  flutter_tts: ^4.0.2
  http: ^1.2.1
  image: ^4.5.2
  image_picker: ^1.1.1
  intl: ^0.19.0
  local_auth: ^2.3.0
  markdown: ^7.3.0
  ollama_dart: ^0.2.1
  omni_datetime_picker: ^2.0.6
  package_info_plus: ^8.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pwa_install: ^0.0.6
  scroll_to_index: ^3.0.1
  simple_icons: ^14.6.1
  smooth_page_indicator: ^1.1.0
  speech_to_text: ^7.0.0
  table_calendar: ^3.1.3
  timezone: ^0.10.0
  transparent_image: ^2.0.1
  universal_html: ^2.2.4
  url_launcher: ^6.2.6
  uuid: ^4.5.1
  version: ^3.0.2
  visibility_detector: ^0.4.0+2
  volume_controller: ^3.2.0
  introduction_screen: ^3.1.17
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1
  build_runner: ^2.4.8
 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo512.png
    - assets/logo512_light.png
    - assets/logo512error.png
    - assets/images/firstpage.png
    - assets/images/secondpage.png
    - assets/images/thirdpage.png
    - assets/images/fourthpage.png
    - assets/images/fifthpage.png