// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT5nukHS5-GVzZJLNr4V2D6t-VH-y3EkA',
    appId: '1:75998063417:web:5e06efdc8a23197a2ed6e8',
    messagingSenderId: '75998063417',
    projectId: 'ite4116m-final-year-proj-3d5c1',
    authDomain: 'ite4116m-final-year-proj-3d5c1.firebaseapp.com',
    storageBucket: 'ite4116m-final-year-proj-3d5c1.firebasestorage.app',
    measurementId: 'G-S40YPT5L6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOGsjmsCx6olQEcPgu2ojqTXSjLYHWBw8',
    appId: '1:75998063417:android:3c474711c53a6c922ed6e8',
    messagingSenderId: '75998063417',
    projectId: 'ite4116m-final-year-proj-3d5c1',
    storageBucket: 'ite4116m-final-year-proj-3d5c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGImJsk9s6fAWIZ36KDqJWDwiIRiRcf2s',
    appId: '1:75998063417:ios:c7bb3af0fffbe1662ed6e8',
    messagingSenderId: '75998063417',
    projectId: 'ite4116m-final-year-proj-3d5c1',
    storageBucket: 'ite4116m-final-year-proj-3d5c1.firebasestorage.app',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGImJsk9s6fAWIZ36KDqJWDwiIRiRcf2s',
    appId: '1:75998063417:ios:c7bb3af0fffbe1662ed6e8',
    messagingSenderId: '75998063417',
    projectId: 'ite4116m-final-year-proj-3d5c1',
    storageBucket: 'ite4116m-final-year-proj-3d5c1.firebasestorage.app',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT5nukHS5-GVzZJLNr4V2D6t-VH-y3EkA',
    appId: '1:75998063417:web:d9ae4a5f71e39ca72ed6e8',
    messagingSenderId: '75998063417',
    projectId: 'ite4116m-final-year-proj-3d5c1',
    authDomain: 'ite4116m-final-year-proj-3d5c1.firebaseapp.com',
    storageBucket: 'ite4116m-final-year-proj-3d5c1.firebasestorage.app',
    measurementId: 'G-8LFYHTLMSR',
  );
}
